name: app_chat
version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: container_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: AppChat
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: container_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  mongo_data:
  redis_data:

networks:
  app_network:
    driver: bridge